### ISSUE TITLE
SSD1306 dimensions

### ISSUE THREAD

**Issue by DhruvaG2000** [daschr/pico-ssd1306#1]
Can you please specify the dimensions of your tested SSD1306 display?
I seem to own a SSD1306 1.3" display and it does not work well with this library. It shows only 5-10% of the display area and the rest is just white noise

**Comment by daschr** [comment]
I've used a 0.96" display with 128x64 pixels. Did you specified the right width and height when using `ssd1306_init` ?https://github.com/daschr/pico-ssd1306/blob/088f5e68daae73e87293c512da7ab75437cf35bc/ssd1306.h#L86

Make sure that there's no loose connection between the display and the controller, I've experienced your issue caused by that.

**Comment by DhruvaG2000** [comment]
> Did you specified the right width and height when using

Well I just tried `` ssd1306_init(&disp, 128, 32, 0x3C, i2c1); ``
and now I am getting about 30% of the display to show those animations in the example...

**Comment by DhruvaG2000** [comment]
> Make sure that there's no loose connection between the display and the controller,

It helped me when I used external pull up resistors too, and no I dont think there is a loose connection issue here as I have used decent quality wires

**Comment by DhruvaG2000** [comment]
I just tested it using my arduino, and then realized I need an equivalent of ``U8glib.h`` for RPi pico.

Ref. https://create.arduino.cc/projecthub/infoelectorials/project-011-arduino-1-3-i2c-white-oled-display-project-a547d4
